// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A2: what the AI read from a sentence. A draft only: the user checks it before saving.
 */
export type AiDraft = { title: string, 
/**
 * Local `YYYY-MM-DD`.
 */
date: string | null, 
/**
 * Local `HH:mm` (only with a date).
 */
time: string | null, 
/**
 * Only with a time.
 */
durationMinutes: number | null, 
/**
 * "Remind me two days before" → 2880.
 */
reminderMinutes: number | null, };
