// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A1: a task read from a picture. Opens the editor pre-filled; never saved on its own.
 */
export type AiImageDraft = { title: string, date: string | null, time: string | null, durationMinutes: number | null, location: string | null, 
/**
 * Other useful details from the picture (amount, reference, who).
 */
notes: string | null, };
