// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether smart features can run: the user agreed to the consent screen and added a key.
 */
export type AiStatus = { consented: boolean, hasKey: boolean, };
