// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextSize } from "./TextSize";
import type { ThemePreference } from "./ThemePreference";
import type { WeekStart } from "./WeekStart";

/**
 * Basic settings (P1-T16). Every field has a sensible default (PRD R7: nothing is required).
 */
export type AppSettings = { theme: ThemePreference, textSize: TextSize, weekStartsOn: WeekStart, 
/**
 * Local `HH:mm`: when all-day tasks remind you (PRD R3 default 09:00). Used from Phase 2.
 */
defaultReminderTime: string, };
