// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Add or edit an area: its name and colour token key (one of the area colours).
 */
export type AreaInput = { name: string, color: string, };
