// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A life area (Work, Home, …). `color` is a design-token key such as `area.work`.
 */
export type Area = { id: string, name: string, color: string, 
/**
 * Lucide icon name, e.g. `briefcase`.
 */
icon: string, sortOrder: number, isArchived: boolean, };
