// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A file attached to an item (P2-T11). The file itself lives in Kairos' attachments folder.
 */
export type Attachment = { id: string, itemId: string, 
/**
 * The original file name, shown to the user.
 */
fileName: string, mime: string, sizeBytes: number, createdAt: string, };
