// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a backup file lives: Kairos's own backups folder, or the user's chosen extra folder.
 */
export type BackupLocation = "app" | "folder";
