// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BackupSettings = { 
/**
 * Extra folder (e.g. a OneDrive/Dropbox folder or USB drive), if chosen.
 */
folder: string | null, lastBackupAt: string | null, 
/**
 * Set when the most recent backup attempt failed (e.g. the disk is full).
 */
lastFailureAt: string | null, };
