// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupKind } from "./BackupKind";
import type { BackupLocation } from "./BackupLocation";

export type BackupInfo = { fileName: string, location: BackupLocation, kind: BackupKind, 
/**
 * UTC ISO-8601.
 */
createdAt: string, sizeBytes: number, 
/**
 * Items in the backup, or None if it could not be read.
 */
itemCount: number | null, };
