// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A5: the local hours (`start_hour` ≤ h < `end_hour`) you tick most tasks done, learned on
 * this computer from the last 8 weeks.
 */
export type BestHours = { startHour: number, endHour: number, 
/**
 * Tasks done in those hours, out of `total`.
 */
done: number, total: number, };
