// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One sub-step of an item.
 */
export type ChecklistItem = { id: string, itemId: string, text: string, done: boolean, sortOrder: number, };
