// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Editor input: the full list in display order. Entries with an `id` update that step;
 * entries without one are new; existing steps missing from the list move to the Trash.
 */
export type ChecklistEntryInput = { id: string | null, text: string, done: boolean, };
