// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Item } from "./Item";

/**
 * My Day data, grouped by time window. The status engine (P1-T06) decides each item's
 * status, and P1-T08 places items into Now / Today / Slipped / This week / Done today.
 */
export type Dashboard = { 
/**
 * Not finished, scheduled at any time today (includes events in progress).
 */
today: Array<Item>, 
/**
 * Unfinished **tasks** scheduled before today (only tasks can slip): the most recent
 * `OVERDUE_SHOWN`, oldest first, plus routines' latest missed occurrences.
 */
overdue: Array<Item>, 
/**
 * How many stored tasks slipped in all (more than `overdue` holds when there are many).
 */
overdueTotal: number, 
/**
 * Not finished, scheduled after today and before the end of the week.
 */
thisWeek: Array<Item>, 
/**
 * Completed today.
 */
doneToday: Array<Item>, };
