// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * "Now" for My Day, computed by the frontend in the user's timezone.
 */
export type DashboardQuery = { 
/**
 * Current instant, UTC.
 */
now: string, 
/**
 * Local midnight today and tomorrow, as UTC instants.
 */
dayStart: string, dayEnd: string, 
/**
 * Today's local date, `YYYY-MM-DD`.
 */
today: string, 
/**
 * End of "this week" (exclusive), as a UTC instant and as a local date.
 */
weekEnd: string, weekEndDate: string, };
