// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A visible calendar range. The frontend owns the user's timezone, so it sends the range
 * both as UTC instants (for timed items) and as local dates (for date-only items).
 * Both ends are exclusive at the end: `[start, end)` and `[startDate, endDate)`.
 */
export type DateRange = { start: string, end: string, startDate: string, endDate: string, };
