// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which occurrences an edit or delete of a repeating item applies to.
 */
export type EditScope = "this" | "following";
