// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a failed command sends to the frontend: stable code, i18n key, and the
 * offending field for validation errors. Never paths, SQL, or user data.
 */
export type ErrorPayload = { code: string, message: string, field: string | null, };
