// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One wishlist entry (PRD R19). Kind: `idea` | `frustration` | `bug`;
 * status: `open` | `planned` | `done`.
 */
export type Feedback = { id: string, kind: string, text: string, 
/**
 * Where it was written (a screen name), if the user chose to include it.
 */
context: string | null, status: string, createdAt: string, };
