// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One stretch of focused work (PRD R16). Pausing ends it; resuming starts another.
 */
export type FocusSession = { id: string, itemId: string | null, startedAt: string, endedAt: string | null, plannedMinutes: number, };
