// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Focused time in a range for one life area (`None` = no task, or a task without an area).
 */
export type FocusTotal = { areaId: string | null, seconds: number, };
