// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Goal = { id: string, title: string, description: string | null, areaId: string | null, 
/**
 * Local `YYYY-MM-DD`.
 */
targetDate: string | null, achievedAt: string | null, };
