// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GoalInput = { title: string, description: string | null, areaId: string | null, targetDate: string | null, };
