// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Habit = { id: string, title: string, areaId: string | null, 
/**
 * `daily` or `weekly:N` (N times per week).
 */
frequency: string, createdAt: string, };
