// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Habit } from "./Habit";

/**
 * A habit with its progress as of a local day.
 */
export type HabitStatus = { habit: Habit, doneToday: boolean, 
/**
 * Days (daily) or weeks (weekly) in a row; 0 = paused.
 */
streak: number, thisWeek: number, 
/**
 * Ticks per week to aim for (7 for daily).
 */
perWeek: number, 
/**
 * Ticked local dates (`YYYY-MM-DD`) in the last 12 weeks, for the heatmap.
 */
recent: Array<string>, };
