// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImportSummary = { imported: number, 
/**
 * Already in Kairos (same title at the same moment).
 */
duplicates: number, 
/**
 * Things Kairos can't represent (cancelled entries, changed single occurrences…).
 */
skipped: number, 
/**
 * Imported without their repeat (a repeat Kairos doesn't support).
 */
simplified: number, };
