// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InboxEntry = { id: string, text: string | null, hasImage: boolean, createdAt: string, };
