// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChecklistItem } from "./ChecklistItem";
import type { Item } from "./Item";

/**
 * An item with everything the editor shows.
 */
export type ItemDetail = { item: Item, checklist: Array<ChecklistItem>, };
