// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemKind } from "./ItemKind";
import type { ItemSource } from "./ItemSource";

/**
 * Everything the item editor can set. Used for create and for full-replace update.
 */
export type ItemInput = { kind: ItemKind, title: string, notes: string | null, areaId: string | null, 
/**
 * 0 none, 1 low, 2 medium, 3 high.
 */
priority: number, 
/**
 * Timed items: any RFC 3339 timestamp; stored normalised to UTC.
 */
startAt: string | null, endAt: string | null, 
/**
 * Date-only items: local `YYYY-MM-DD`. Cannot be combined with `start_at`.
 */
dueDate: string | null, location: string | null, 
/**
 * Ignored on update. Defaults to `manual`.
 */
source: ItemSource | null, 
/**
 * Reminder offsets in minutes before the item's moment (0 = at the time; whole days keep
 * the clock time). Omitted: a new item gets the default reminder (PRD R3), an edited item
 * keeps its reminders. Empty: no reminders.
 */
reminders?: Array<number>, };
