// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ItemFilters = { 
/**
 * Only these life areas; empty means all areas.
 */
areaIds: Array<string>, };
