// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How an item was created (ARCHITECTURE §4 `items.source`).
 */
export type ItemSource = "manual" | "quick" | "nlp" | "ai_image" | "template" | "import";
