// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemKind } from "./ItemKind";
import type { ItemSource } from "./ItemSource";

/**
 * A task or event exactly as stored. Status is never stored; it is computed (P1-T06).
 *
 * Scheduling shapes:
 * - date-only (all-day): `due_date` set, `start_at`/`end_at` null, `all_day` true
 * - timed: `start_at` set (events also have `end_at`), `due_date` null
 * - unscheduled (Inbox): all three null
 */
export type Item = { id: string, kind: ItemKind, title: string, notes: string | null, areaId: string | null, 
/**
 * 0 none, 1 low, 2 medium, 3 high.
 */
priority: number, allDay: boolean, 
/**
 * UTC ISO-8601, e.g. `2026-10-07T13:00:00.000Z`.
 */
startAt: string | null, endAt: string | null, 
/**
 * Local calendar date `YYYY-MM-DD`.
 */
dueDate: string | null, completedAt: string | null, skippedAt: string | null, location: string | null, rrule: string | null, recurrenceParentId: string | null, originalStartAt: string | null, milestoneId: string | null, rescheduleCount: number, source: ItemSource, createdAt: string, updatedAt: string, deletedAt: string | null, };
