// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the query was found, so the palette can say why an item matched.
 */
export type MatchedIn = "title" | "notes" | "step" | "area";
