// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Milestone = { id: string, goalId: string, title: string, targetDate: string | null, sortOrder: number, };
