// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Milestone } from "./Milestone";

/**
 * Progress counts tasks linked to a milestone (not repeating series): done of all.
 */
export type MilestoneProgress = { milestone: Milestone, done: number, total: number, };
