// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThemePreference } from "./ThemePreference";

/**
 * The welcome screens' answers. Anything left out keeps its default.
 */
export type OnboardingInput = { name: string, theme: ThemePreference | null, 
/**
 * Life areas to keep; the other default areas are archived (not deleted).
 */
keepAreaIds: Array<string> | null, };
