// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OnboardingStatus = { 
/**
 * Show the welcome screens (first launch, not finished or skipped yet).
 */
needed: boolean, 
/**
 * How many sample tasks are still around (for "Remove sample tasks").
 */
samplesLeft: number, };
