// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlanBusy = { title: string, 
/**
 * Local `HH:mm`.
 */
start: string, end: string, };
