// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanBusy } from "./PlanBusy";

export type PlanDay = { 
/**
 * Local `YYYY-MM-DD`.
 */
date: string, busy: Array<PlanBusy>, };
