// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One proposed slot. The user accepts all, some or none.
 */
export type PlanProposal = { taskId: string, date: string, 
/**
 * Local `HH:mm`.
 */
start: string, durationMinutes: number, };
