// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanDay } from "./PlanDay";
import type { PlanTask } from "./PlanTask";

/**
 * A3 "Plan my day / week": what the frontend sends. Local wall-clock strings only; only
 * task titles and lengths and the busy times' titles go to the AI (PRD §7.3).
 */
export type PlanRequest = { 
/**
 * What the user asked, e.g. "around my Thursday meeting". May be empty.
 */
instruction: string, 
/**
 * Local `YYYY-MM-DDTHH:mm`.
 */
now: string, 
/**
 * Local `HH:mm`: plan only inside these hours.
 */
dayStart: string, dayEnd: string, days: Array<PlanDay>, tasks: Array<PlanTask>, 
/**
 * A5: the user's best hours, e.g. "09:00–11:00" (only the range, never the history).
 */
preferredHours?: string, };
