// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlanTask = { id: string, title: string, 
/**
 * The task's own length, if it has one.
 */
durationMinutes: number | null, };
