// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * New schedule for `reschedule_item` (drag on the calendar, the slipped-items card).
 */
export type ScheduleInput = { startAt: string | null, endAt: string | null, dueDate: string | null, };
