// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Shown once after startup if Kairos had to repair its data (P1-T15).
 */
export type StartupNotice = { "kind": "restored", backupCreatedAt: string, keptAt: string, } | { "kind": "unrecoverable", keptAt: string, };
