// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemKind } from "./ItemKind";

/**
 * One item of a template, with its day relative to the template's first day.
 */
export type TemplateEntry = { kind: ItemKind, title: string, notes: string | null, areaId: string | null, priority: number, 
/**
 * Days after the day the template is inserted at (0 = that day).
 */
dayOffset: number, 
/**
 * Local `HH:MM`, or none for an all-day item.
 */
time: string | null, durationMinutes: number | null, steps: Array<string>, };
