// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TemplateEntry } from "./TemplateEntry";

export type Template = { id: string, name: string, entries: Array<TemplateEntry>, createdAt: string, };
