// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * DESIGN_SYSTEM §4: Small 0.9, Default 1.0, Large 1.125, Extra large 1.25.
 */
export type TextSize = "small" | "default" | "large" | "xl";
