// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A newer Kairos that can be installed (P4-T05).
 */
export type UpdateInfo = { version: string, 
/**
 * Release notes, if the release has any.
 */
notes: string | null, };
